/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class naoki_smallpt_SmallPTLibs */

#define MATH_PI 3.14159265358979323846;
#define MATH_PI2 6.283185307179586;

#ifndef _Included_naoki_smallpt_SmallPTLibs
#define _Included_naoki_smallpt_SmallPTLibs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     naoki_smallpt_SmallPTLibs
 * Method:    createXDRay
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_naoki_smallpt_SmallPTLibs_createXDRay
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
